### ISSUE TITLE
github-check reporter shows clippy as step under random job

### ISSUE THREAD

**Issue by wmmc88** [giraffate/clippy-action#83]
When using `github-check` reporter, a PR's checks tab will show `clippy-action`'s check under a random job.  

```
 - name: Run Cargo Clippy
        uses: giraffate/clippy-action@v1
        with:
          tool_name: Clippy
          clippy_flags: --locked --profile ${{ matrix.cargo_profile }} --all-targets -- -D warnings
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: nofilter
          fail_on_error: true
```

When run with the above config (and triggered by a push), the resulting check will show up under a random job (i think its the first job to start). Example:
<img width="484" alt="image" src="https://github.com/giraffate/clippy-action/assets/16629657/145f6c9a-722d-4500-aebc-a9ed99aa4b84">

The above clippy check(triggered by **push**) is a step in the Lint job, but in the Checks tab of **the PR**, it shows under the Test Job (on other executions, it shows under different Jobs).
